    <?php include_once 'head.html' ?>
    <link href="css/about.css" rel="stylesheet" type="text/css">
    <meta property="og:title" content="NachoToast About Page">
    <meta property="og:description" content="About page for the NachoToast website.">
    <meta property="og:site_name" content="NachoToast">
    <meta property="og:image" content="https://nachotoast.com/img/main.png">
    <title>About</title>
</head>
<body>
    <?php
        session_start();
        include_once 'header.php' ;
    ?>
    <div id="about">
        <h1>About</h1>
        <p>This website, the server that hosts it, and other things it hosts are all part of a project/hobby to help me learn more computer science related things.<br>Anything made here is done because it was fun to make, challenging, or just because I felt like it.</p>
        <h2>Server</h2>
        <p>The physical server is built and hosted locally. In terms of hardware it runs an <span class="hardware" title="ASUS Prime B450M-A mATX AM4 [$140.99]">mATX motherboard</span>, <span class="hardware" title="Crucial BX500 240GB 520/500 Read/Write (MB/s) [$53.99]">240GB SSD</span>, <span class="hardware" title="HyperX Fure 8GB DDR$-2666MHz CL16 (1x8GB) [$78.99]">8GB RAM</span>, <span class="hardware" title="Gigabyte GeForce GT1030 2GB GDDR5 1506MHz (Obsolete) [$143.75]">GT1030</span>, <span class="hardware" title="Cooler Master MWE V2 450W 80+ Bronze [$74.99]">450W Bronze PSU</span>, and a <span class="hardware" title="AMD Ryzen 5 2600 6C 12T 3.4GHz [$255]">Ryzen 5 2600 (6C, 3.4Ghz)</span>. Combined with a <span class="hardware" title="Aerocool CS-100 mATX [$48.98]">case</span> and a cable, the total cost of the server was <span style='color: pink'>$802.23 NZD</span>.</p>
        <h2>Website</h2>
        <p>The website is hosted on the above server using XAMPP.</p>
        <p>SSL Certificates are generated by LetsEncrypt (via CertBot).</p>
        <p>The <span style='color: pink'>NachoToast.com</span> domain costs approximately <span style='color: pink'>$8 NZD</span> a year under Cloudflare, and the <span style='color: pink'>ntgc.ddns.net</span> domain is freely registered under no-ip.com, with built-in DDNS.</p>
        <h2>Other Software</h2>
        <p>NachoBot runs as a PM2 process using Discord.js and Node.</p>
        <p>Minecraft runs on Java 11 and (normally) on Paper Spigot.</p>
        <p>The server runs Ubuntu 20.04.</p>
    </div>
</body>
</html>